# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='Note'),
            preserve_default=False,
        ),
    ]
